server:
  port: 8080


spring:
  application:
    name: "todo-api"
  datasource:
    url: jdbc:mysql://db-p0faj.pub-cdb.ntruss.com:3306/mjconnect?allowPublicKeyRetrieval=true
    username: semyung
    password: tpaud123$

  jpa:
    show-sql: true